name = "react_gleam"
version = "0.4.0"

licences = ["MIT"]
description = "React bindings for Gleam"
repository = { type = "github", user = "brettkolodny", repo = "https://github.com/brettkolodny/react-gleam"}

target = "javascript"

[dependencies]
gleam_stdlib = "~> 0.25"
gleam_javascript = "~> 0.2"

[dev-dependencies]
gleeunit = "~> 0.7"
