name = "react_gleam"
version = "0.5.0"

licences = ["MIT"]
description = "React bindings for Gleam"
repository = { type = "github", user = "brettkolodny", repo = "react-gleam"}

target = "javascript"

[dependencies]
gleam_stdlib = "~> 0.28.2"
gleam_javascript = "~> 0.4"

[dev-dependencies]
gleeunit = "~> 0.7"
