name = "react_gleam"
version = "0.5.1"

licences = ["MIT"]
description = "React bindings for Gleam"
repository = { type = "github", user = "brettkolodny", repo = "react-gleam"}

target = "javascript"
gleam = ">= 0.32.0"

[dependencies]
gleam_stdlib = "~> 0.31"
gleam_javascript = "~> 0.7"

[dev-dependencies]
gleeunit = "~> 0.7"
