name = "react_gleam"
version = "0.5.1"

licences = ["MIT"]
description = "React bindings for Gleam"
repository = { type = "github", user = "brettkolodny", repo = "react-gleam" }

target = "javascript"

[dependencies]
gleam_stdlib = ">= 0.63.2 and < 1.0.0"
gleam_javascript = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.6.1 and < 2.0.0"
