name = "react_gleam"
version = "0.3.0"

target = "javascript"

licences = ["MIT"]
description = "React bindings for Gleam"

[dependencies]
gleam_stdlib = "~> 0.25"
gleam_javascript = "~> 0.2"

[dev-dependencies]
gleeunit = "~> 0.7"
